import os
import sys
import time
import subprocess
import RPi.GPIO as GPIO
from threading import Thread




File=open("/lib/dhcpcd/dhcpcd-hooks/Write-40-route","r")

Cl1=File.readline()
Cl_R1=File.readline()
Cl_R2=File.readline()
Cl_R3=File.readline()
print(Cl1)

#print(type(MasterOrClient_Status))
File.close()




Write_Routes_File = open("/lib/dhcpcd/dhcpcd-hooks/40-route","w+")
if( len(Cl1) != 0):
    if(len(Cl_R1) != 0):
        Write_Routes_File.write("#ip route add " + Cl_R1.rstrip("\n")  + " via " + Cl1.rstrip("\n") + "\n")
    else:
        Write_Routes_File.write("\n")
    if(len(Cl_R2) != 0):
        Write_Routes_File.write("#ip route add " + Cl_R2.rstrip("\n")  + " via " + Cl1.rstrip("\n") + "\n")
    else:
        Write_Routes_File.write("\n")
    if(len(Cl_R3) != 0):
        Write_Routes_File.write("#ip route add " + Cl_R3.rstrip("\n")  + " via " + Cl1.rstrip("\n") + "\n")
    else:
        Write_Routes_File.write("\n")

Write_Routes_File.close()




##iptables = open("/etc/iptables/iptables.rules","w+")
##
##iptables.write("# Generated by iptables-save v1.6.0 on Wed Jan 23 15:32:56 2019")
##iptables.write("\n")
##iptables.write("#*filter")
##iptables.write("\n")
##iptables.write("#:INPUT ACCEPT [13553:932172]")
##iptables.write("\n")
##iptables.write("#:FORWARD ACCEPT [0:0]")
##iptables.write("\n")
##iptables.write("#:OUTPUT ACCEPT [14250:994905]")
##iptables.write("\n")
##iptables.write("#-A FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT")
##iptables.write("\n")
##iptables.write("#-A FORWARD -i eth0 -o wlan0 -j ACCEPT")
##iptables.write("\n")
##iptables.write("#COMMIT")
##iptables.write("\n")
##iptables.write("# Completed on Wed Jan 23 15:32:56 2019")
##iptables.write("\n")
##iptables.write("# Generated by iptables-save v1.6.0 on Wed Jan 23 15:32:56 2019")
##iptables.write("\n")
##iptables.write("#*nat")
##iptables.write("\n")
##iptables.write("#:PREROUTING ACCEPT [4109:294613]")
##iptables.write("\n")
##iptables.write("#:INPUT ACCEPT [2969:203735]")
##iptables.write("\n")
##iptables.write("#:OUTPUT ACCEPT [784:52776]")
##iptables.write("\n")
##iptables.write("#:POSTROUTING ACCEPT [762:51068]")
##iptables.write("\n")
##iptables.write("#-A POSTROUTING -o wlan0 -j MASQUERADE")
##iptables.write("\n")
##iptables.write("#COMMIT")
##iptables.write("\n")
##iptables.write("# Completed on Wed Jan 23 15:32:56 2019")
##iptables.write("\n")
##
##iptables.close()


# Generated by iptables-save v1.6.0 on Wed Jan 23 15:32:56 2019
#*filter
#:INPUT ACCEPT [13553:932172]
#:FORWARD ACCEPT [0:0]
#:OUTPUT ACCEPT [14250:994905]
#-A FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
#-A FORWARD -i eth0 -o wlan0 -j ACCEPT
#COMMIT
# Completed on Wed Jan 23 15:32:56 2019
# Generated by iptables-save v1.6.0 on Wed Jan 23 15:32:56 2019
#*nat
#:PREROUTING ACCEPT [4109:294613]
#:INPUT ACCEPT [2969:203735]
#:OUTPUT ACCEPT [784:52776]
#:POSTROUTING ACCEPT [762:51068]
#-A POSTROUTING -o wlan0 -j MASQUERADE
#COMMIT
# Completed on Wed Jan 23 15:32:56 2019

